!**********************************************************************
! Globally accessible variables
!**********************************************************************
module global

  use constants
  
  implicit none

  save

  ! Verbose output
  logical     :: verbose
  
  ! Number of bra and ket MOs
  integer(is) :: nmoB,nmoK

  ! Number of bra and ket electrons
  integer(is)              :: nelB,nelK,nel_alphaB,nel_alphaK,&
                              nel_betaB,nel_betaK

  ! Bra-ket MO overlaps
  real(dp), allocatable    :: smo(:,:)
  
  ! Determinant bit strings
  integer(is)              :: n_intB,n_intK
  integer(is)              :: ndetB,ndetK
  integer(ib), allocatable :: detB(:,:,:), detK(:,:,:)

  ! Eigenvectors
  integer(is)              :: nrootsB,nrootsK
  real(dp), allocatable    :: vecB(:,:),vecK(:,:)

  ! Number of unique alpha and beta strings
  integer(is)              :: nalphaB,nbetaB,nalphaK,nbetaK

  ! Unique alpha and beta strings
  integer(ib), allocatable :: alphaB(:,:),betaB(:,:),&
                              alphaK(:,:),betaK(:,:)

  ! Alpha string offsets
  integer(is), allocatable :: offsetB(:),offsetK(:)

  ! Detetrminant-to-beta-string mapping
  integer(is), allocatable :: det2betaB(:),det2betaK(:)

  ! Unique beta factors
  real(dp), allocatable    :: betafac(:,:)

  ! Fixed-occupation orbital information
  integer(is)              :: nfixed_alpha,nfixed_beta
  
  ! Determinant thresholds
  real(dp), parameter      :: hthrsh=1e-6_dp
  real(dp), parameter      :: fthrsh=1e-6_dp

  !
  ! Dyson orbital-specific variables
  !
  ! Here, sigma refers to the spin index of the annihilation
  ! operators and tau the 'other' spin
  !
  ! sigma and tau spin indices (1<->alpha, 2<->beta)
  integer(is)              :: isigma,itau

  ! Number of sigma and tau electrons
  integer(is)              :: nel_sigmaB,nel_tauB,nel_sigmaK,nel_tauK
  
  ! Number of unique sigma and tau strings
  integer(is)              :: nsigmaB,ntauB,nsigmaK,ntauK
  
  ! Unique sigma and tau strings
  integer(ib), allocatable :: sigmaB(:,:),tauB(:,:),&
                              sigmaK(:,:),tauK(:,:)

  ! Number of unique ket sigma-holes
  integer(is)              :: nsigmaHK
  
  ! Unique ket sigma-hole strings
  integer(ib), allocatable :: sigmaHK(:,:)

  ! Detetrminant-to-tau-string mapping
  integer(is), allocatable :: det2tauB(:),det2tauK(:)

  ! Irreps generated by the bra and ket wave functions
  integer(is)              :: irrepB,irrepK

  ! Irreps generated the bra and ket MOs
  integer(ib), allocatable :: mosymB(:),mosymK(:)

  ! Sigma-hole string info
  integer(is)              :: Hinfo_dim
  integer(is), allocatable :: Hinfo(:,:)

  ! Sigma-hole info offsets
  integer(is), allocatable :: offHinfo(:)

  ! Unique tau factors
  real(dp), allocatable    :: taufac(:,:)
  
end module global
