!**********************************************************************
! Routines for the calculation of the determinant expansions of MRCI
! wave functions
!**********************************************************************
module csf2det

  implicit none

contains

!######################################################################
! get_detdim: determines the number of determinants generated by a
!             given configuration basis
!######################################################################
  subroutine get_detdim(cfg,detdim)

    use constants
    use bitglobal
    use conftype
    use mrciutils

    implicit none

    ! MRCI configuration derived type
    type(mrcfg), intent(in)  :: cfg

    ! Size of the determinant basis
    integer(is), intent(out) :: detdim

    ! Everyting else
    integer(is)              :: nopen,iconf

    !
    ! Initialisation
    !
    detdim=0

    !
    ! Reference space confs
    !
    do iconf=1,cfg%n0h
       nopen=sop_nopen(cfg%sop0h(:,:,iconf),cfg%n_int_I)
       detdim=detdim+ndets(nopen)
    enddo
    
    !
    ! 1I confs
    !
    do iconf=1,cfg%n1I
       nopen=sop_nopen(cfg%sop1I(:,:,iconf),n_int)
       detdim=detdim+ndets(nopen)       
    enddo

    !
    ! 2I confs
    !
    do iconf=1,cfg%n2I
       nopen=sop_nopen(cfg%sop2I(:,:,iconf),n_int)
       detdim=detdim+ndets(nopen)       
    enddo

    !
    ! 1E confs
    !
    do iconf=1,cfg%n1E
       nopen=sop_nopen(cfg%sop1E(:,:,iconf),n_int)
       detdim=detdim+ndets(nopen)       
    enddo

    !
    ! 2E confs
    !
    do iconf=1,cfg%n2E
       nopen=sop_nopen(cfg%sop2E(:,:,iconf),n_int)
       detdim=detdim+ndets(nopen)       
    enddo

    !
    ! 1I1E confs
    !
    do iconf=1,cfg%n1I1E
       nopen=sop_nopen(cfg%sop1I1E(:,:,iconf),n_int)
       detdim=detdim+ndets(nopen)       
    enddo

    return
    
  end subroutine get_detdim
    
!######################################################################
! csf2det: master routine controling the calculation of a set of MRCI
!          wave functions in the determinant basis
!######################################################################
  subroutine csf2det_mrci(cfg,nroots,csfdim,detdim,vec_csf,vec_det)

    use constants
    use bitglobal
    use conftype
    use mrciutils
    
    implicit none

    ! MRCI configuration derived type
    type(mrcfg), intent(in)  :: cfg

    ! Dimensions
    integer(is), intent(in)  :: nroots,csfdim,detdim

    ! Eigenvectors in the CSF and determinant bases
    real(dp), intent(in)     :: vec_csf(csfdim,nroots)
    real(dp), intent(out)    :: vec_det(detdim,nroots)

    ! CSF -> det transformation matrix
    real(dp), allocatable    :: transmat(:,:,:)
    
    ! Everything else
    integer(is)              :: n,nopen,ncsf,ndet,iconf
    integer(is)              :: icsf,jcsf,idet,jdet

!----------------------------------------------------------------------
! CSF -> det transformation matrix
!----------------------------------------------------------------------
    ! Allocate array
    allocate(transmat(maxdet,maxcsf,0:nomax))
    transmat=0.0d0

    ! Nopen = 0 case
    transmat(1,1,0)=1.0d0

    ! Nopen > 0 cases
    do n=1,nomax
       transmat(:,:,n)=transpose(csfcoe(:,:,n))
    enddo
    
!----------------------------------------------------------------------
! Initialisation
!----------------------------------------------------------------------
    ! Eigenvectors in the determinant basis
    vec_det=0.0d0

    ! CSF and determinant counters
    icsf=1
    jcsf=0
    idet=1
    jdet=0
    
!----------------------------------------------------------------------
! Ref space confs
!----------------------------------------------------------------------
    do iconf=1,cfg%n0h

       ! No. open shells
       nopen=sop_nopen(cfg%sop0h(:,:,iconf),cfg%n_int_I)
       
       ! No. CSFs & determinants
       ndet=ndets(nopen)
       ncsf=ncsfs(nopen)

       ! End points in the CSF and determinant basis eigenvectors
       jcsf=icsf+ncsf-1
       jdet=idet+ndet-1

       ! Determinant coefficicients
       do n=1,nroots
          vec_det(idet:jdet,n)=matmul(transmat(1:ndet,1:ncsf,nopen),&
               vec_csf(icsf:jcsf,n))
       enddo
          
       ! Start points in CSF and determinant basis eigenvectors for
       ! the next iteration
       icsf=jcsf+1
       idet=jdet+1
       
    enddo

!----------------------------------------------------------------------
! 1I confs
!----------------------------------------------------------------------
    do iconf=1,cfg%n1I

       ! No. open shells
       nopen=sop_nopen(cfg%sop1I(:,:,iconf),n_int)
       
       ! No. CSFs & determinants
       ndet=ndets(nopen)
       ncsf=ncsfs(nopen)

       ! End points in the CSF and determinant basis eigenvectors
       jcsf=icsf+ncsf-1
       jdet=idet+ndet-1

       ! Determinant coefficicients
       do n=1,nroots
          vec_det(idet:jdet,n)=matmul(transmat(1:ndet,1:ncsf,nopen),&
               vec_csf(icsf:jcsf,n))
       enddo
       
       ! Start points in CSF and determinant basis eigenvectors for
       ! the next iteration
       icsf=jcsf+1
       idet=jdet+1
       
    enddo

!----------------------------------------------------------------------
! 2I confs
!----------------------------------------------------------------------
    do iconf=1,cfg%n2I

       ! No. open shells
       nopen=sop_nopen(cfg%sop2I(:,:,iconf),n_int)
       
       ! No. CSFs & determinants
       ndet=ndets(nopen)
       ncsf=ncsfs(nopen)

       ! End points in the CSF and determinant basis eigenvectors
       jcsf=icsf+ncsf-1
       jdet=idet+ndet-1

       ! Determinant coefficicients
       do n=1,nroots
          vec_det(idet:jdet,n)=matmul(transmat(1:ndet,1:ncsf,nopen),&
               vec_csf(icsf:jcsf,n))
       enddo
       
       ! Start points in CSF and determinant basis eigenvectors for
       ! the next iteration
       icsf=jcsf+1
       idet=jdet+1
       
    enddo

!----------------------------------------------------------------------
! 1E confs
!----------------------------------------------------------------------
    do iconf=1,cfg%n1E

       ! No. open shells
       nopen=sop_nopen(cfg%sop1E(:,:,iconf),n_int)
       
       ! No. CSFs & determinants
       ndet=ndets(nopen)
       ncsf=ncsfs(nopen)

       ! End points in the CSF and determinant basis eigenvectors
       jcsf=icsf+ncsf-1
       jdet=idet+ndet-1

       ! Determinant coefficicients
       do n=1,nroots
          vec_det(idet:jdet,n)=matmul(transmat(1:ndet,1:ncsf,nopen),&
               vec_csf(icsf:jcsf,n))
       enddo
       
       ! Start points in CSF and determinant basis eigenvectors for
       ! the next iteration
       icsf=jcsf+1
       idet=jdet+1
       
    enddo

!----------------------------------------------------------------------
! 2E confs
!----------------------------------------------------------------------
    do iconf=1,cfg%n2E

       ! No. open shells
       nopen=sop_nopen(cfg%sop2E(:,:,iconf),n_int)
       
       ! No. CSFs & determinants
       ndet=ndets(nopen)
       ncsf=ncsfs(nopen)

       ! End points in the CSF and determinant basis eigenvectors
       jcsf=icsf+ncsf-1
       jdet=idet+ndet-1

       ! Determinant coefficicients
       do n=1,nroots
          vec_det(idet:jdet,n)=matmul(transmat(1:ndet,1:ncsf,nopen),&
               vec_csf(icsf:jcsf,n))
       enddo
       
       ! Start points in CSF and determinant basis eigenvectors for
       ! the next iteration
       icsf=jcsf+1
       idet=jdet+1
       
    enddo

!----------------------------------------------------------------------
! 1I1E confs
!----------------------------------------------------------------------
    do iconf=1,cfg%n1I1E

       ! No. open shells
       nopen=sop_nopen(cfg%sop1I1E(:,:,iconf),n_int)
       
       ! No. CSFs & determinants
       ndet=ndets(nopen)
       ncsf=ncsfs(nopen)

       ! End points in the CSF and determinant basis eigenvectors
       jcsf=icsf+ncsf-1
       jdet=idet+ndet-1

       ! Determinant coefficicients
       do n=1,nroots
          vec_det(idet:jdet,n)=matmul(transmat(1:ndet,1:ncsf,nopen),&
               vec_csf(icsf:jcsf,n))
       enddo
       
       ! Start points in CSF and determinant basis eigenvectors for
       ! the next iteration
       icsf=jcsf+1
       idet=jdet+1
       
    enddo

    return
    
  end subroutine csf2det_mrci
  
!######################################################################
  
end module csf2det
