#!/bin/bash

#
# CMake options
#
args=""
for var in "$@"; do
    args+=" $var"
done

#args+=" -DHDF5_INC_DIR=~/software/hdf5/include -DHDF5_LIB_DIR=~/software/hdf5/lib"

#args+=" -DHDF5_INC_DIR=/usr/include/hdf5/serial -DHDF5_LIB_DIR=/usr/lib/x86_64-linux-gnu/hdf5/serial"

args+=" -DHDF5_INC_DIR=/home/simon/software/hdf5-1.12.0/hdf5/include"
args+=" -DHDF5_LIB_DIR=/home/simon/software/hdf5-1.12.0/hdf5/lib"

#
# Make the build directory
#
if [ -d build ]; then
    rm -r build/*
else
    mkdir build
fi

#
# Move into the build directory and build and install bitlib
#
cd build
cmake ../ -DCBINDING=ON -DCMAKE_INSTALL_PREFIX=.. $args
make
make install
