#!/bin/bash

#
# Conditional compilation flags
#
args=""
for var in "$@"; do
    args+=" $var"
done

#args+=" -DHDF5_INC_DIR=/usr/include/hdf5/serial"
#args+=" -DHDF5_LIB_DIR=/usr/lib/x86_64-linux-gnu/hdf5/serial"

#args+=" -DHDF5_INC_DIR=/globalhome/sneville/software/hdf5-1.12.0/hdf5/include"
#args+=" -DHDF5_LIB_DIR=/globalhome/sneville/software/hdf5-1.12.0/hdf5/lib"

args+=" -DHDF5_INC_DIR=/home/simon/software/hdf5-1.12.0/hdf5/include"
args+=" -DHDF5_LIB_DIR=/home/simon/software/hdf5-1.12.0/hdf5/lib"

args+=" -DHDF5_INC_DIR=/home/schuurm/software/hdf5/include"
args+=" -DHDF5_LIB_DIR=/home/schuurm/software/hdf5/lib"

#
# Make the build directory
#
if [ -d build ]; then
    rm -r build/*
else
    mkdir build
fi

#
# Move into the build directory and build and install bitci
#
cd build
cmake ../ -DCBINDING=ON -DCMAKE_INSTALL_PREFIX=.. $args
make
make install
cd ../

#
# Compile the documentation
#
pdflatex_path=`which pdflatex`
if [ -z $pdflatex_path ]; then
    echo
    echo "pdflatex not found: skipping the documentation compilation"
    echo
else
    echo
    echo "Compiling the documentation..."
    cd doc
#    pdflatex symmetry.tex &>/dev/null
#    pdflatex implementation.tex &>/dev/null
#    bibtex implementation.aux &>/dev/null
#    pdflatex implementation.tex &>/dev/null
#    pdflatex implementation.tex &>/dev/null
    cd ../
fi
