!**********************************************************************
! Routines for the calculation of 1-RDMs for MRCI wavefunctions
!**********************************************************************
module rdm

  implicit none

contains

!######################################################################
! 1rdm_mrci: Master routine for the calculation of MRCI 1-RDMs for
!            a specified set of states of a single irrep
!######################################################################
  subroutine rdm_mrci(cfg,csfdim,nroots,vec,dmat)

    use constants
    use bitglobal
    use conftype
    use iomod
    use timing
    
    implicit none

    ! No. CSFs
    integer(is), intent(in) :: csfdim
    
    ! No. roots for which the RDMs will be computed
    integer(is), intent(in) :: nroots
    
    ! MRCI configuration derived type
    type(mrcfg), intent(in) :: cfg

    ! Eigenvectors
    real(dp), intent(in)    :: vec(csfdim,nroots)
    
    ! Density matrix
    real(dp), intent(out)   :: dmat(nmo,nmo,nroots)
   
    ! Timing variables
    real(dp)                 :: tcpu_start,tcpu_end,twall_start,&
                                twall_end 
    
!----------------------------------------------------------------------
! Start timing
!----------------------------------------------------------------------
    call get_times(twall_start,tcpu_start)  
    
!----------------------------------------------------------------------
! Initialisation
!----------------------------------------------------------------------
    dmat=0.0d0

!----------------------------------------------------------------------
! (1) On-diagonal elements
!----------------------------------------------------------------------
    call rdm_mrci_diag(cfg,csfdim,nroots,vec,dmat)
    
!----------------------------------------------------------------------
! (2) Off-diagonal elements of the Ref-Ref block
!----------------------------------------------------------------------
    call rdm_mrci_0h_0h(cfg,csfdim,nroots,vec,dmat)
    
!----------------------------------------------------------------------
! Stop timing and print report
!----------------------------------------------------------------------
    call get_times(twall_end,tcpu_end)
    call report_times(twall_end-twall_start,tcpu_end-tcpu_start,&
         'rdm_mrci')
    
    return
    
  end subroutine rdm_mrci

!######################################################################
! rdm_mrci_ondiag: Calculation of the on-diagonal elements of the MRCI
!                  1-RDMs
!######################################################################
  subroutine rdm_mrci_diag(cfg,csfdim,nroots,vec,dmat)

    use constants
    use bitglobal
    use conftype
    use mrciutils
    use iomod
    
    implicit none

    ! No. CSFs
    integer(is), intent(in) :: csfdim
    
    ! No. roots for which the RDMs will be computed
    integer(is), intent(in) :: nroots
    
    ! MRCI configuration derived type
    type(mrcfg), intent(in) :: cfg

    ! Eigenvectors
    real(dp), intent(in)    :: vec(csfdim,nroots)
    
    ! Density matrix
    real(dp), intent(inout) :: dmat(nmo,nmo,nroots)

    ! Working arrays
    integer(ib)             :: conf_full(n_int,2)
    integer(ib)             :: sop_full(n_int,2)
        
    ! MO classes
    integer(is)             :: socc(nmo),docc(nmo),unocc(nmo)
    integer(is)             :: nsocc,ndocc,nunocc
    
    ! Everything else
    integer(is)             :: iconf,iomega,icsf
    integer(is)             :: i,n,ista,imo,ioff
    integer(is)             :: n_int_I
    real(dp)                :: c2,trace

!----------------------------------------------------------------------
! Initialisation
!----------------------------------------------------------------------
    ! N_int^I
    n_int_I=cfg%n_int_I
    
!----------------------------------------------------------------------
! Reference space configurations
!----------------------------------------------------------------------
    ! Loop over reference configurationd
    do iconf=1,cfg%n0h

       ! Get the lists of singly-occupied and doubly-occupied MOs
       call sop_socc_list(cfg%sop0h(:,:,iconf),n_int_I,socc,nmo,nsocc)
       call sop_docc_list(cfg%sop0h(:,:,iconf),n_int_I,docc,nmo,ndocc)

       ! Loop over roots
       do ista=1,nroots

          ! Loop over CSFs generated by this configuration
          do icsf=cfg%csfs0h(iconf),cfg%csfs0h(iconf+1)-1

             ! Coefficient squared
             c2=vec(icsf,ista)**2

             ! Singly-occupied MO contributions to the 1-RDM
             do i=1,nsocc
                imo=socc(i)
                dmat(imo,imo,ista)=dmat(imo,imo,ista)+c2
             enddo

             ! Doubly-occupied MO contributions to the 1-RDM
             do i=1,ndocc
                imo=docc(i)
                dmat(imo,imo,ista)=dmat(imo,imo,ista)+2.0d0*c2
             enddo
             
          enddo
          
       enddo
       
    enddo

!----------------------------------------------------------------------
! 1I configurations
!----------------------------------------------------------------------
    if (cfg%n1I > 0) then

       ! Loop over 1-hole configurations
       do n=1,cfg%n1h

          ! Loop over the 1I configurations generated by the
          ! current 1-hole configuration
          do ioff=cfg%off1I(n),cfg%off1I(n+1)-1

             ! Get the lists of singly-occupied and doubly-occupied MOs
             call sop_socc_list(cfg%sop1I(:,:,ioff),n_int,socc,&
                  nmo,nsocc)
             call sop_docc_list(cfg%sop1I(:,:,ioff),n_int,docc,&
                  nmo,ndocc)

             ! Loop over roots
             do ista=1,nroots
                
                ! Loop over CSFs generated by this configuration
                do icsf=cfg%csfs1I(ioff),cfg%csfs1I(ioff+1)-1
                   
                   ! Coefficient squared
                   c2=vec(icsf,ista)**2
                   
                   ! Singly-occupied MO contributions to the 1-RDM
                   do i=1,nsocc
                      imo=socc(i)
                      dmat(imo,imo,ista)=dmat(imo,imo,ista)+c2
                   enddo
                   
                   ! Doubly-occupied MO contributions to the 1-RDM
                   do i=1,ndocc
                      imo=docc(i)
                      dmat(imo,imo,ista)=dmat(imo,imo,ista)+2.0d0*c2
                   enddo
                   
                enddo
          
             enddo
             
          enddo
             
       enddo

    endif

!----------------------------------------------------------------------
! 2I configurations
!----------------------------------------------------------------------
    if (cfg%n2I > 0) then

       ! Loop over 2-hole configurations
       do n=1,cfg%n2h

          ! Loop over the 2I configurations generated by the
          ! current 2-hole configuration
          do ioff=cfg%off2I(n),cfg%off2I(n+1)-1

             ! Get the lists of singly-occupied and doubly-occupied MOs
             call sop_socc_list(cfg%sop2I(:,:,ioff),n_int,socc,&
                  nmo,nsocc)
             call sop_docc_list(cfg%sop2I(:,:,ioff),n_int,docc,&
                  nmo,ndocc)

             ! Loop over roots
             do ista=1,nroots
                
                ! Loop over CSFs generated by this configuration
                do icsf=cfg%csfs2I(ioff),cfg%csfs2I(ioff+1)-1
                   
                   ! Coefficient squared
                   c2=vec(icsf,ista)**2
                   
                   ! Singly-occupied MO contributions to the 1-RDM
                   do i=1,nsocc
                      imo=socc(i)
                      dmat(imo,imo,ista)=dmat(imo,imo,ista)+c2
                   enddo
                   
                   ! Doubly-occupied MO contributions to the 1-RDM
                   do i=1,ndocc
                      imo=docc(i)
                      dmat(imo,imo,ista)=dmat(imo,imo,ista)+2.0d0*c2
                   enddo
                   
                enddo
          
             enddo
             
          enddo
             
       enddo

    endif

!----------------------------------------------------------------------
! 1E configurations
!----------------------------------------------------------------------
    if (cfg%n1E > 0) then

       ! Loop over 1-hole configurations
       do n=1,cfg%n1h

          ! Loop over the 1E configurations generated by the
          ! current 1-hole configuration
          do ioff=cfg%off1E(n),cfg%off1E(n+1)-1

             ! Get the lists of singly-occupied and doubly-occupied MOs
             call sop_socc_list(cfg%sop1E(:,:,ioff),n_int,socc,&
                  nmo,nsocc)
             call sop_docc_list(cfg%sop1E(:,:,ioff),n_int,docc,&
                  nmo,ndocc)

             ! Loop over roots
             do ista=1,nroots
                
                ! Loop over CSFs generated by this configuration
                do icsf=cfg%csfs1E(ioff),cfg%csfs1E(ioff+1)-1
                   
                   ! Coefficient squared
                   c2=vec(icsf,ista)**2
                   
                   ! Singly-occupied MO contributions to the 1-RDM
                   do i=1,nsocc
                      imo=socc(i)
                      dmat(imo,imo,ista)=dmat(imo,imo,ista)+c2
                   enddo
                   
                   ! Doubly-occupied MO contributions to the 1-RDM
                   do i=1,ndocc
                      imo=docc(i)
                      dmat(imo,imo,ista)=dmat(imo,imo,ista)+2.0d0*c2
                   enddo
                   
                enddo
          
             enddo
             
          enddo
             
       enddo

    endif

!----------------------------------------------------------------------
! 2E configurations
!----------------------------------------------------------------------
    if (cfg%n2E > 0) then

       ! Loop over 2-hole configurations
       do n=1,cfg%n2h

          ! Loop over the 2E configurations generated by the
          ! current 2-hole configuration
          do ioff=cfg%off2E(n),cfg%off2E(n+1)-1

             ! Get the lists of singly-occupied and doubly-occupied MOs
             call sop_socc_list(cfg%sop2E(:,:,ioff),n_int,socc,&
                  nmo,nsocc)
             call sop_docc_list(cfg%sop2E(:,:,ioff),n_int,docc,&
                  nmo,ndocc)

             ! Loop over roots
             do ista=1,nroots
                
                ! Loop over CSFs generated by this configuration
                do icsf=cfg%csfs2E(ioff),cfg%csfs2E(ioff+1)-1
                   
                   ! Coefficient squared
                   c2=vec(icsf,ista)**2
                   
                   ! Singly-occupied MO contributions to the 1-RDM
                   do i=1,nsocc
                      imo=socc(i)
                      dmat(imo,imo,ista)=dmat(imo,imo,ista)+c2
                   enddo
                   
                   ! Doubly-occupied MO contributions to the 1-RDM
                   do i=1,ndocc
                      imo=docc(i)
                      dmat(imo,imo,ista)=dmat(imo,imo,ista)+2.0d0*c2
                   enddo
                   
                enddo
          
             enddo
             
          enddo
             
       enddo

    endif

!----------------------------------------------------------------------
! 1I1E configurations
!----------------------------------------------------------------------
    if (cfg%n1I1E > 0) then

       ! Loop over 2-hole configurations
       do n=1,cfg%n2h

          ! Loop over the 1I1E configurations generated by the
          ! current 2-hole configuration
          do ioff=cfg%off1I1E(n),cfg%off1I1E(n+1)-1

             ! Get the lists of singly-occupied and doubly-occupied MOs
             call sop_socc_list(cfg%sop1I1E(:,:,ioff),n_int,socc,&
                  nmo,nsocc)
             call sop_docc_list(cfg%sop1I1E(:,:,ioff),n_int,docc,&
                  nmo,ndocc)

             ! Loop over roots
             do ista=1,nroots
                
                ! Loop over CSFs generated by this configuration
                do icsf=cfg%csfs1I1E(ioff),cfg%csfs1I1E(ioff+1)-1
                   
                   ! Coefficient squared
                   c2=vec(icsf,ista)**2
                   
                   ! Singly-occupied MO contributions to the 1-RDM
                   do i=1,nsocc
                      imo=socc(i)
                      dmat(imo,imo,ista)=dmat(imo,imo,ista)+c2
                   enddo
                   
                   ! Doubly-occupied MO contributions to the 1-RDM
                   do i=1,ndocc
                      imo=docc(i)
                      dmat(imo,imo,ista)=dmat(imo,imo,ista)+2.0d0*c2
                   enddo
                   
                enddo
          
             enddo
             
          enddo
             
       enddo

    endif

!----------------------------------------------------------------------
! Sanity check on the traces of the 1-RDMs
!----------------------------------------------------------------------
    ! Loop over roots
    do ista=1,nroots
       trace=0.0d0
       ! Loop over MOs
       do imo=1,nmo
          trace=trace+dmat(imo,imo,ista)
       enddo
       ! Exit here if the trace of the 1-RDM does not equal the
       ! no. electrons
       if (abs(trace-nelB) > 1e-10_dp) then
          errmsg='Incorrect Tr(rho) in rdm_mrci_diag'
          call error_control
       endif
    enddo
    
    return
    
  end subroutine rdm_mrci_diag
    
!######################################################################
! rdm_mrci_0h_0h: Calculation of the off-diagonal elements of the
!                 Ref-Ref block of the MRCI 1-RDMs
!######################################################################  
  subroutine rdm_mrci_0h_0h(cfg,csfdim,nroots,vec,dmat)

    use constants
    use bitglobal
    use conftype
    
    implicit none

    ! No. CSFs
    integer(is), intent(in) :: csfdim
    
    ! No. roots for which the RDMs will be computed
    integer(is), intent(in) :: nroots
    
    ! MRCI configuration derived type
    type(mrcfg), intent(in) :: cfg

    ! Eigenvectors
    real(dp), intent(in)    :: vec(csfdim,nroots)
    
    ! Density matrix
    real(dp), intent(inout) :: dmat(nmo,nmo,nroots)

    print*,'>Here?'

    return
    
  end subroutine rdm_mrci_0h_0h
    
!######################################################################
  
end module rdm
