#!/bin/bash

#
# Conditional compilation flags
#
args=""
for var in "$@"; do
    args+=" $var"
done

#
# Build all the libraries
#
topdir=`pwd`
for lib in overlap bitci; do

    cd $lib

    if [ -d build ]; then
	rm -r build/*
    else
	mkdir build
    fi

    cd build
    cmake ../ -DCMAKE_INSTALL_PREFIX=../../ $args
    make
    make install
    
    cd $topdir
    
done

