!**********************************************************************
! Calculation of information about the discarded (Q-space)
! configurations
!**********************************************************************
module qspace

  implicit none
  
contains

!######################################################################
! qspace_e2: computes the contributions to the 2nd-order ENPT2 energy
!            corrections from the Q-space configurations
!######################################################################
  subroutine qspace_e2(cfg,csfdim,nvec,Avec,hdiag,E0,i1I,i2I,i1E,&
       i2E,i1I1E,n1I,n2I,n1E,n2E,n1I1E,E2Q)

    use constants
    use bitglobal
    use conftype
    
    implicit none

    ! MRCI configuration derived type
    type(mrcfg), intent(in)  :: cfg
    
    ! Dimensions
    integer(is), intent(in)  :: csfdim,nvec,n1I,n2I,n1E,n2E,n1I1E

    ! A-vectors
    real(dp), intent(in)     :: Avec(csfdim,nvec)

    ! On-diagonal Hamiltonian matrix elements
    real(dp), intent(in)     :: hdiag(csfdim)

    ! Zeroth-order (ref space) energies
    real(dp), intent(in)     :: E0(nvec)
    real(dp)                 :: eig0(nvec)
    
    ! Surviving configuration flags
    integer(is), intent(in)  :: i1I(n1I),i2I(n2I),i1E(n1E),i2E(n2E),&
                                i1I1E(n1I1E)

    ! Q-space contributions to the 2nd-order energy corrections
    real(dp), intent(out)    :: E2Q(nvec)
    
    ! Everything else
    integer(is)              :: n,ioff,icsf,j
    real(dp)                 :: f

!----------------------------------------------------------------------
! Subtract off E_SCF and E_nuc from the energies to get the true
! reference space eigenvalues
!----------------------------------------------------------------------    
    eig0=E0-escf-enuc
    
!----------------------------------------------------------------------
! Initialisation
!----------------------------------------------------------------------
    E2Q=0.0d0
    
!----------------------------------------------------------------------
! Q-space 1I contributions
!----------------------------------------------------------------------
    if (cfg%n1I > 0) then
       
       ! Loop over 1-hole configurations
       do n=1,cfg%n1h

          ! Loop over the 1I configurations generated by the 1-hole
          ! configuration
          do ioff=cfg%off1I(n),cfg%off1I(n+1)-1

             ! Cycle if we are at a P-space configuration
             if (i1I(ioff) == 1) cycle

             ! Loop over states
             do j=1,nvec
             
                ! Loop over CSFs generated by this configuration
                do icsf=cfg%csfs1I(ioff),cfg%csfs1I(ioff+1)-1

                   ! Contribution to the Q-space energy correction
                   f=Avec(icsf,j)*(eig0(j)-hdiag(icsf))
                   E2Q(j)=E2Q(j)+f**2/(eig0(j)-hdiag(icsf))
                
                enddo

             enddo
             
          enddo
          
       enddo

    endif

!----------------------------------------------------------------------
! Q-space 1E contributions
!----------------------------------------------------------------------
    if (cfg%n1E > 0) then
       
       ! Loop over 1-hole configurations
       do n=1,cfg%n1h

          ! Loop over the 1E configurations generated by the 1-hole
          ! configuration
          do ioff=cfg%off1E(n),cfg%off1E(n+1)-1

             ! Cycle if we are at a P-space configuration
             if (i1E(ioff) == 1) cycle

             ! Loop over states
             do j=1,nvec
             
                ! Loop over CSFs generated by this configuration
                do icsf=cfg%csfs1E(ioff),cfg%csfs1E(ioff+1)-1

                   ! Contribution to the Q-space energy correction
                   f=Avec(icsf,j)*(eig0(j)-hdiag(icsf))
                   E2Q(j)=E2Q(j)+f**2/(eig0(j)-hdiag(icsf))
                
                enddo

             enddo
             
          enddo
          
       enddo

    endif
    
!----------------------------------------------------------------------
! Q-space 2I contributions
!----------------------------------------------------------------------
    if (cfg%n2I > 0) then
       
       ! Loop over 2-hole configurations
       do n=1,cfg%n2h

          ! Loop over the 2I configurations generated by the 2-hole
          ! configuration
          do ioff=cfg%off2I(n),cfg%off2I(n+1)-1

             ! Cycle if we are at a P-space configuration
             if (i2I(ioff) == 1) cycle

             ! Loop over states
             do j=1,nvec
             
                ! Loop over CSFs generated by this configuration
                do icsf=cfg%csfs2I(ioff),cfg%csfs2I(ioff+1)-1

                   ! Contribution to the Q-space energy correction
                   f=Avec(icsf,j)*(eig0(j)-hdiag(icsf))
                   E2Q(j)=E2Q(j)+f**2/(eig0(j)-hdiag(icsf))
                
                enddo

             enddo
             
          enddo
          
       enddo

    endif

!----------------------------------------------------------------------
! Q-space 2E contributions
!----------------------------------------------------------------------
    if (cfg%n2E > 0) then
       
       ! Loop over 2-hole configurations
       do n=1,cfg%n2h

          ! Loop over the 2E configurations generated by the 2-hole
          ! configuration
          do ioff=cfg%off2E(n),cfg%off2E(n+1)-1

             ! Cycle if we are at a P-space configuration
             if (i2E(ioff) == 1) cycle

             ! Loop over states
             do j=1,nvec
             
                ! Loop over CSFs generated by this configuration
                do icsf=cfg%csfs2E(ioff),cfg%csfs2E(ioff+1)-1

                   ! Contribution to the Q-space energy correction
                   f=Avec(icsf,j)*(eig0(j)-hdiag(icsf))
                   E2Q(j)=E2Q(j)+f**2/(eig0(j)-hdiag(icsf))
                
                enddo

             enddo
             
          enddo
          
       enddo

    endif
    

!----------------------------------------------------------------------
! Q-space 1I1E contributions
!----------------------------------------------------------------------
    if (cfg%n1I1E > 0) then
       
       ! Loop over 2-hole configurations
       do n=1,cfg%n2h

          ! Loop over the 1I1E configurations generated by the 2-hole
          ! configuration
          do ioff=cfg%off1I1E(n),cfg%off1I1E(n+1)-1

             ! Cycle if we are at a P-space configuration
             if (i1I1E(ioff) == 1) cycle

             ! Loop over states
             do j=1,nvec
             
                ! Loop over CSFs generated by this configuration
                do icsf=cfg%csfs1I1E(ioff),cfg%csfs1I1E(ioff+1)-1

                   ! Contribution to the Q-space energy correction
                   f=Avec(icsf,j)*(eig0(j)-hdiag(icsf))
                   E2Q(j)=E2Q(j)+f**2/(eig0(j)-hdiag(icsf))
                
                enddo

             enddo
             
          enddo
          
       enddo

    endif
    
    return
    
  end subroutine qspace_e2

!######################################################################
  
end module qspace
