#!/usr/bin/env python
'''
Redefine the main SCF kernel in PyCSF
'''
import numpy
import scipy.linalg
from pyscf import lib
from pyscf.lib import logger
from pyscf.scf import diis
from pyscf.scf import chkfile
from pdft import project
from pyscf import __config__

TIGHT_GRAD_CONV_TOL = getattr(__config__, 'scf_hf_kernel_tight_grad_conv_tol', True)

def kernel(ks, conv_tol=1e-10, conv_tol_grad=None,
           dump_chk=True, dm0=None, callback=None, conv_check=True, **kwargs):
    '''kernel: the SCF driver for Projected Hybrid DFT (PDFT).

    Args:
        ks : an instance of KohnShamPDFT class
            ks object holds all parameters to control SCF.  One can modify its
            member functions to change the behavior of SCF.  The member
            functions which are called in kernel are

            | ks.get_init_guess
            | ks.get_hcore
            | ks.get_ovlp
            | ks.get_veff
            | ks.get_fock
            | ks.get_grad
            | ks.eig
            | ks.get_occ
            | ks.make_rdm1
            | ks.energy_tot
            | ks.dump_chk

    Kwargs:
        conv_tol : float
            converge threshold.
        conv_tol_grad : float
            gradients converge threshold.
        dump_chk : bool
            Whether to save SCF intermediate results in the checkpoint file
        dm0 : ndarray
            Initial guess density matrix.  If not given (the default), the kernel
            takes the density matrix generated by ``ks.get_init_guess``.
        callback : function(envs_dict) => None
            callback function takes one dict as the argument which is
            generated by the builtin function :func:`locals`, so that the
            callback function can access all local variables in the current
            environment.
        sap_basis : str
            SAP basis name

    Returns:
        A list :   scf_conv, e_tot, mo_energy, mo_coeff, mo_occ

        scf_conv : bool
            True means SCF converged
        e_tot : float
            Hartree-Fock energy of last iteration
        mo_energy : 1D float array
            Orbital energies.  Depending the eig function provided by ks
            object, the orbital energies may NOT be sorted.
        mo_coeff : 2D array
            Orbital coefficients.
        mo_occ : 1D array
            Orbital occupancies.  The occupancies may NOT be sorted from large
            to small.

    Examples:

    >>> from pyscf import gto, scf
    >>> mol = gto.M(atom='H 0 0 0; H 0 0 1.1', basis='cc-pvdz')
    >>> conv, e, mo_e, mo, mo_occ = scf.hf.kernel(scf.hf.SCF(mol), dm0=numpy.eye(mol.nao_nr()))
    >>> print('conv = %s, E(HF) = %.12f' % (conv, e))
    conv = True, E(HF) = -1.081170784378
    '''
    if 'init_dm' in kwargs:
        raise RuntimeError('''
You see this error message because of the API updates in pyscf v0.11.
Keyword argument "init_dm" is replaced by "dm0"''')
    cput0 = (logger.process_clock(), logger.perf_counter())
    if conv_tol_grad is None:
        conv_tol_grad = numpy.sqrt(conv_tol)
        logger.info(ks, 'Set gradient conv threshold to %g', conv_tol_grad)

    mol = ks.mol
    s1e = ks.get_ovlp(mol)

    ## Build Projector
    if ks.SQQS is None:
        ks.build_proj(mo_coeff=None) ## sets ks.SQQS object
        # if built via project.build_mo_proj, initial guess used for mo_coeff.
    ##

    if dm0 is None:
        dm = ks.get_init_guess(mol, ks.init_guess, s1e=s1e, **kwargs)
    else:
        dm = dm0
    h1e = ks.get_hcore(mol)
    vhf = ks.get_veff(mol, dm)
    e_tot = ks.energy_tot(dm, h1e, vhf)
    logger.info(ks, 'init E= %.15g', e_tot)

    scf_conv = False
    mo_energy = mo_coeff = mo_occ = None

    # Skip SCF iterations. Compute only the total energy of the initial density
    if ks.max_cycle <= 0:
        fock = ks.get_fock(h1e, s1e, vhf, dm)  # = h1e + vhf, no DIIS
        mo_energy, mo_coeff = ks.eig(fock, s1e)
        mo_occ = ks.get_occ(mo_energy, mo_coeff)
        return scf_conv, e_tot, mo_energy, mo_coeff, mo_occ

    if isinstance(ks.diis, lib.diis.DIIS):
        ks_diis = ks.diis
    elif ks.diis:
        assert issubclass(ks.DIIS, lib.diis.DIIS)
        ks_diis = ks.DIIS(ks, ks.diis_file)
        ks_diis.space = ks.diis_space
        ks_diis.rollback = ks.diis_space_rollback
        ks_diis.damp = ks.diis_damp

        # We get the used orthonormalized AO basis from any old eigendecomposition.
        # Since the ingredients for the Fock matrix has already been built, we can
        # just go ahead and use it to determine the orthonormal basis vectors.
        fock = ks.get_fock(h1e, s1e, vhf, dm)
        _, ks_diis.Corth = ks.eig(fock, s1e)
    else:
        ks_diis = None

    if dump_chk and ks.chkfile:
        # Explicit overwrite the mol object in chkfile
        # Note in pbc.scf, mf.mol == mf.cell, cell is saved under key "mol"
        chkfile.save_mol(mol, ks.chkfile)

    # A preprocessing hook before the SCF iteration
    ks.pre_kernel(locals())
    fock_last = None
    cput1 = logger.timer(ks, 'initialize scf', *cput0)
    ks.cycles = 0
    for cycle in range(ks.max_cycle):
        dm_last = dm
        last_hf_e = e_tot

        fock = ks.get_fock(h1e, s1e, vhf, dm, cycle, ks_diis, fock_last=fock_last)
        mo_energy, mo_coeff = ks.eig(fock, s1e)
        ks.build_proj(mo_coeff=mo_coeff) ## (**kwargs) mo_coeff ignored if use_ext_basis
        mo_occ = ks.get_occ(mo_energy, mo_coeff)
        dm = ks.make_rdm1(mo_coeff, mo_occ)
        vhf = ks.get_veff(mol, dm, dm_last, vhf)
        e_tot = ks.energy_tot(dm, h1e, vhf)

        # Here Fock matrix is h1e + vhf, without DIIS.  Calling get_fock
        # instead of the statement "fock = h1e + vhf" because Fock matrix may
        # be modified in some methods.
        fock_last = fock
        fock = ks.get_fock(h1e, s1e, vhf, dm)  # = h1e + vhf, no DIIS
        norm_gorb = numpy.linalg.norm(ks.get_grad(mo_coeff, mo_occ, fock))
        if not TIGHT_GRAD_CONV_TOL:
            norm_gorb = norm_gorb / numpy.sqrt(norm_gorb.size)
        norm_ddm = numpy.linalg.norm(dm-dm_last)
        logger.info(ks, 'cycle= %d E= %.15g  delta_E= %4.3g  |g|= %4.3g  |ddm|= %4.3g',
                    cycle+1, e_tot, e_tot-last_hf_e, norm_gorb, norm_ddm)

        if callable(ks.check_convergence):
            scf_conv = ks.check_convergence(locals())
        elif abs(e_tot-last_hf_e) < conv_tol and norm_gorb < conv_tol_grad:
            scf_conv = True

        if dump_chk and ks.chkfile:
            ks.dump_chk(locals())

        if callable(callback):
            callback(locals())

        cput1 = logger.timer(ks, 'cycle= %d'%(cycle+1), *cput1)

        if scf_conv:
            break

    ks.cycles = cycle + 1
    if scf_conv and conv_check:
        # An extra diagonalization, to remove level shift
        #fock = ks.get_fock(h1e, s1e, vhf, dm)  # = h1e + vhf
        mo_energy, mo_coeff = ks.eig(fock, s1e)
        ks.build_proj(mo_coeff=mo_coeff) ## (**kwargs) mo_coeff ignored if use_ext_basis
        mo_occ = ks.get_occ(mo_energy, mo_coeff)
        dm, dm_last = ks.make_rdm1(mo_coeff, mo_occ), dm
        vhf = ks.get_veff(mol, dm, dm_last, vhf)
        e_tot, last_hf_e = ks.energy_tot(dm, h1e, vhf), e_tot

        fock = ks.get_fock(h1e, s1e, vhf, dm)
        norm_gorb = numpy.linalg.norm(ks.get_grad(mo_coeff, mo_occ, fock))
        if not TIGHT_GRAD_CONV_TOL:
            norm_gorb = norm_gorb / numpy.sqrt(norm_gorb.size)
        norm_ddm = numpy.linalg.norm(dm-dm_last)

        conv_tol = conv_tol * 10
        conv_tol_grad = conv_tol_grad * 3
        if callable(ks.check_convergence):
            scf_conv = ks.check_convergence(locals())
        elif abs(e_tot-last_hf_e) < conv_tol or norm_gorb < conv_tol_grad:
            scf_conv = True
        logger.info(ks, 'Extra cycle  E= %.15g  delta_E= %4.3g  |g|= %4.3g  |ddm|= %4.3g',
                    e_tot, e_tot-last_hf_e, norm_gorb, norm_ddm)
        if dump_chk and ks.chkfile:
            ks.dump_chk(locals())

    logger.timer(ks, 'scf_cycle', *cput0)
    # A post-processing hook before return
    ks.post_kernel(locals())
    return scf_conv, e_tot, mo_energy, mo_coeff, mo_occ
